### ISSUE TITLE
Quest build is broken due to matrix types mixup

### ISSUE THREAD

**Issue by nevyn** [alloverse/allovisor#47]
Reported by Jost Grant:

> Latest build (apk on site & sideload from SideQuest) fails on the (well at least my, lol) Quest2.

![image](https://user-images.githubusercontent.com/34791/212703326-5ccd65e9-10e8-476b-acf8-3b7335b8f134.png)

**Comment by elenapalombini** [comment]
I got the same error on the Quest 1.
